name: TMT~spg
favicon: null
layout_spectrum: 0.09278098028153181
typography_spectrum: 0.3917396978940815
title: TMT ~ special projects group
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6720909988507628
  lightness: 0.6149256806820631
  saturation: 0.009885800071060658
  rhythmicContrast: 0.5946252483408898
purpose: []
