name: TMT~spg
favicon: null
layout_spectrum: 0.74203
typography_spectrum: 0.3917396978940815
title: TMT ~ special projects group
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ef0937'
    - '#0aef0c'
    - '#f9f9f9'
    - '#8e8e8e'
  brandStrength: 1
  lightness: 0.6149256806820631
  saturation: 0.4375
  rhythmicContrast: 0.5946252483408898
purpose: []
